- name: Google Java Format

  uses: axel-op/googlejavaformat-action@v4.0.0

  on:
    push:
      branches:
      - main

jobs:
  formatting:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v4
        with:
          args: "--skip-sorting-imports --replace"
